# Generated by Django 4.0.3 on 2022-04-05 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothesresourcing_app', '0002_alter_institution_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='donation',
            managers=[
            ],
        ),
    ]
