# Generated by Django 4.0.3 on 2022-04-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothesresourcing_app', '0004_alter_donation_pick_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(default='Brak uwag', null=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.IntegerField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna')], default=1),
        ),
    ]
